name: Deploy to Fly Production

on:
  push:
      branches: [production]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_LITERPC_DEPLOY }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy lite-rpc
        run: flyctl deploy -c cd/lite-rpc-mainnet.toml --remote-only
